# Generated by Django 5.0.1 on 2024-02-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Femail', 'female'), ('Other', 'other')], default='male', max_length=50),
        ),
    ]
