# Generated by Django 5.0.1 on 2024-02-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_employee_id_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
