# Generated by Django 5.0.1 on 2024-02-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.CharField(choices=[('administration', 'Administration'), ('system_administration', 'System_Administration'), ('application_developer', 'Application_Developer'), ('security_administration', 'Security_Administration'), ('database_administration', 'Database_Administration'), ('web_developer', 'Web_Developer'), ('helpdesk_supporter', 'Helpdesk_Supporter'), ('technical_supporter', 'Technical_Supporter')], max_length=50),
        ),
    ]
